'use strict';
(()=>{
  const A=window.BSO_APP,{PART_B,PART_C}=A.R,$=A.$,$$=A.$$,esc=A.esc,nl=A.nl;
  const meta=()=>`${esc(A.data.meta.company||'Unternehmen')} · ${esc(A.data.meta.site||'Standort')} · ${esc(A.data.meta.area||'Geltungsbereich')} · Dok.-Nr. ${esc(A.data.meta.documentNo||'–')} · Version ${esc(A.data.meta.version||'–')}`;
  const header=(title,part)=>`<header class="doc-head"><div class="doc-title"><span>Brandschutzordnung</span><h1>${esc(title)}</h1></div><div class="part-badge">Teil ${part}</div></header><div class="doc-meta">${meta()}</div>`;
  const sign=(type,code,label,symbol)=>`<div class="safety-sign ${type}" aria-label="${esc(label)}"><span class="sign-symbol">${symbol}</span><small>${esc(code)}</small></div>`;
  A.renderA=()=>`<div class="a-frame"><div class="a-inner">
    <header class="a-title"><span>BRANDSCHUTZORDNUNG</span><h1>BRÄNDE VERHÜTEN</h1><p>${esc(A.data.meta.company||'Unternehmen')} · ${esc(A.data.meta.site||'Standort')}</p></header>
    <section class="a-prevent">${sign('prohibition','P002 / P003','Rauchen und offene Flamme verboten','◉')}<div><h2>Brände verhüten</h2><p>${nl(A.data.partA.prevent)}</p></div></section>
    <h1 class="emergency-title">VERHALTEN IM BRANDFALL</h1><div class="a-calm"><b>Ruhe bewahren</b></div>
    <section class="a-step">${sign('fire','F005 / F006','Brand melden','☎')}<div><h2>Brand melden</h2><p>${nl(A.data.partA.report)}</p><dl><div><dt>Notruf</dt><dd>${esc(A.data.alarm.emergencyNumber||'112')}</dd></div>${A.data.alarm.internalNumber?`<div><dt>Intern</dt><dd>${esc(A.data.alarm.internalNumber)}</dd></div>`:''}<div><dt>Alarmierung</dt><dd>${esc(A.data.alarm.alarmMethod||'–')}</dd></div></dl></div></section>
    <section class="a-step">${sign('rescue','E001/E002 · E007','In Sicherheit bringen','↗')}<div><h2>In Sicherheit bringen</h2><p>${nl(A.data.partA.rescue)}</p><dl><div><dt>Sammelstelle</dt><dd>${esc(A.data.alarm.assemblyPoint||'–')}</dd></div><div><dt>Alarm</dt><dd>${esc(A.data.alarm.alarmSignal||'–')}</dd></div></dl></div></section>
    <section class="a-step">${sign('fire','F001','Feuerlöscher','▰')}<div><h2>Löschversuch unternehmen</h2><p>${nl(A.data.partA.extinguish)}</p></div></section>
    <footer class="a-extra"><b>Besondere Festlegung</b><span>${nl(A.data.partA.extra)}</span><small>Dok.-Nr. ${esc(A.data.meta.documentNo||'–')} · Version ${esc(A.data.meta.version||'–')} · Stand ${esc(A.data.meta.validFrom||'–')}</small></footer>
  </div></div>`;
  const cover=part=>`<section class="doc-page cover-page">${header(`Teil ${part}`,part)}<div class="cover-center"><span>BRANDSCHUTZORDNUNG</span><h2>Teil ${part}</h2><p>${part==='B'?'für Personen ohne besondere Brandschutzaufgaben':'für Personen mit besonderen Brandschutzaufgaben'}</p></div><dl class="cover-data"><div><dt>Unternehmen</dt><dd>${esc(A.data.meta.company||'–')}</dd></div><div><dt>Standort</dt><dd>${esc(A.data.meta.site||'–')}</dd></div><div><dt>Geltungsbereich</dt><dd>${esc(A.data.meta.area||'–')}</dd></div><div><dt>Dokument</dt><dd>${esc(A.data.meta.documentNo||'–')} · Version ${esc(A.data.meta.version||'–')}</dd></div><div><dt>Gültig ab</dt><dd>${esc(A.data.meta.validFrom||'–')}</dd></div><div><dt>Nächste Prüfung</dt><dd>${esc(A.data.meta.nextReview||'–')}</dd></div></dl><div class="workflow"><span>Erstellt: ${esc(A.data.meta.author||'–')}</span><span>Geprüft: ${esc(A.data.meta.reviewer||'–')}</span><span>Freigegeben: ${esc(A.data.meta.approver||'–')}</span></div></section>`;
  const toc=(part,rules)=>`<section class="doc-page">${header(`Inhaltsübersicht – Teil ${part}`,part)}<ol class="toc">${rules.map((x,i)=>`<li><span>${i+1}. ${esc(x.title)}</span><i></i></li>`).join('')}</ol><div class="doc-note"><b>Geltungsbereich</b><p>${nl(A.data.scope.people)}<br>${nl(A.data.scope.specialAreas)}</p></div></section>`;
  const chapters=(part,rules)=>rules.map((x,i)=>`<section class="doc-page chapter-page">${header(`${i+1}. ${x.title}`,part)}<div class="chapter-body">${nl(A.data[`part${part}`][x.key]||'Noch nicht ausgefüllt.')}</div><footer>Brandschutzordnung Teil ${part} · ${esc(A.data.meta.documentNo||'–')} · Version ${esc(A.data.meta.version||'–')}</footer></section>`).join('');
  const roles=()=>{const rows={'Brandschutzbeauftragte/r':A.data.roles.fireOfficer,'Vertretung Brandschutzbeauftragte/r':A.data.roles.deputyFireOfficer,'Räumungsleitung':A.data.roles.evacuationLead,'Vertretung Räumungsleitung':A.data.roles.deputyEvacuationLead,'Brandschutz-/Räumungshelfer':A.data.roles.fireWardens,'Erste Hilfe':A.data.roles.firstAid,'Technischer Dienst':A.data.roles.technicalService,'Pforte / Empfang':A.data.roles.gate,'Umwelt / Löschwasserschutz':A.data.roles.environment,'Werk-/Unternehmensleitung':A.data.roles.management,'Weitere Funktionen':A.data.roles.other};return `<section class="doc-page">${header('Funktionen und Zuständigkeiten','C')}<table class="roles-table"><tbody>${Object.entries(rows).map(([k,v])=>`<tr><th>${esc(k)}</th><td>${nl(v||'–')}</td></tr>`).join('')}</tbody></table></section>`;};
  const release=part=>`<section class="doc-page release-page">${header('Dokumentenlenkung und Freigabe',part)}<table class="release-table"><tr><th>Dokumentnummer</th><td>${esc(A.data.meta.documentNo||'–')}</td><th>Version</th><td>${esc(A.data.meta.version||'–')}</td></tr><tr><th>Gültig ab</th><td>${esc(A.data.meta.validFrom||'–')}</td><th>Nächste Prüfung</th><td>${esc(A.data.meta.nextReview||'–')}</td></tr><tr><th>Änderungsvermerk</th><td colspan="3">${nl(A.data.meta.changeNote||'–')}</td></tr></table><div class="signature-grid"><div><b>Erstellt durch</b><span>${esc(A.data.meta.author||'–')}</span><i>Datum / Unterschrift</i></div><div><b>Geprüft durch</b><span>${esc(A.data.meta.reviewer||'–')}</span><i>Datum / Unterschrift</i></div><div><b>Freigegeben durch</b><span>${esc(A.data.meta.approver||'–')}</span><i>Datum / Unterschrift</i></div></div><div class="doc-note"><b>Verteilung und Unterweisung</b><p>${nl(A.data.distribution.deliveryMethod)}<br>${nl(A.data.distribution.trainingMethod)}</p></div></section>`;
  A.renderLong=part=>{const rules=part==='B'?PART_B:PART_C;return cover(part)+toc(part,rules)+(part==='C'?roles():'')+chapters(part,rules)+release(part);};
  A.renderPreview=()=>{
    if(!A.data.output[A.previewPart]){const p=['A','B','C'].find(x=>A.data.output[x]);if(p)A.previewPart=p;}
    $('#preview').className=`document part-${A.previewPart.toLowerCase()}`;
    $('#preview').innerHTML=A.previewPart==='A'?A.renderA():A.renderLong(A.previewPart);
    $$('#previewTabs button').forEach(b=>{b.classList.toggle('active',b.dataset.preview===A.previewPart);b.disabled=!A.data.output[b.dataset.preview];});
  };
})();
